'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm1
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''MultiView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MultiView1 As Global.System.Web.UI.WebControls.MultiView
    
    '''<summary>
    '''homepageView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents homepageView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''btnHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHome As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnDash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDash As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnWorkOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWorkOrders As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCustomers As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEmployees control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEmployees As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInventory As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gvTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTasks As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvTasksCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTasksCurrent As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvTasksOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvTasksOld As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''rbTaskFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbTaskFilter As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''gvWorkOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWorkOrders As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvWorkOrdersCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWorkOrdersCurrent As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvWorkOrdersOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvWorkOrdersOld As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''rbWorkOrderFilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbWorkOrderFilter As Global.System.Web.UI.WebControls.RadioButtonList
    
    '''<summary>
    '''tbWorkOrderID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderCustomerID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderTaskID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderTaskID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderRecieved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderRecieved As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderCompleted As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderCompletionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderCompletionStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbWorkOrderCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbWorkOrderCost As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddWorkOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddWorkOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateWorkOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateWorkOrder As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlWorkOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWorkOrders As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''tbTaskID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTaskID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTaskDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTaskDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTaskCompletionStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTaskCompletionStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbTaskEmployeeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbTaskEmployeeID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddTask As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnUpdateTask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateTask As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTasks As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''gvCustomers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCustomers As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tbCustomerID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCustomerID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCustomerName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbPhoneNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPhoneNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbCustomerEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCustomerEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbAddress As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddCustomer As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEmployee As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tblEmployeeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmployeeID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tblEmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblEmployeeName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddEmployee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEmployee As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gvInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvInventory As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''gvEquipment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEquipment As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''tbInventoryID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbInventoryID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbEquipmentID_INV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEquipmentID_INV As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbProductName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbProductName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tbQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbQuantity As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddInventory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInventory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnUpdateInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateInventory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClearInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClearInventory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''customerView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customerView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''employeeView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents employeeView As Global.System.Web.UI.WebControls.View
    
    '''<summary>
    '''InventoryView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InventoryView As Global.System.Web.UI.WebControls.View
End Class
